from __future__ import annotations

SKILLS = {
    "coding-agent": "clawlite.skills.coding_agent:run",
    "github": "clawlite.skills.github:run",
    "gmail": "clawlite.skills.gmail:run",
    "google-calendar": "clawlite.skills.google_calendar:run",
    "obsidian": "clawlite.skills.obsidian:run",
    "slack": "clawlite.skills.slack:run",
    "discord": "clawlite.skills.discord:run",
    "twitter": "clawlite.skills.twitter:run",
    "threads": "clawlite.skills.threads:run",
    "web-search": "clawlite.skills.web_search:run",
    "web-fetch": "clawlite.skills.web_fetch:run",
    "browser": "clawlite.skills.browser:run",
    "docker": "clawlite.skills.docker:run",
    "ssh": "clawlite.skills.ssh:run",
    "supabase": "clawlite.skills.supabase:run",
    "firebase": "clawlite.skills.firebase:run",
    "aws": "clawlite.skills.aws:run",
    "vercel": "clawlite.skills.vercel:run",
    "google-drive": "clawlite.skills.google_drive:run",
    "image-gen": "clawlite.skills.image_gen:run",
    "whisper": "clawlite.skills.whisper:run",
    "weather": "clawlite.skills.weather:run",
    "cron": "clawlite.skills.cron:run",
    "skill-creator": "clawlite.skills.skill_creator:run",
    "memory-search": "clawlite.skills.memory_search:run",
    "healthcheck": "clawlite.skills.healthcheck:run",
    "linear": "clawlite.skills.linear:run",
    "notion": "clawlite.skills.notion:run",
    "tailscale": "clawlite.skills.tailscale:run",
    "ollama": "clawlite.skills.ollama:run",
    "pdf": "clawlite.skills.pdf:run",
    "rss": "clawlite.skills.rss:run",
    "youtube": "clawlite.skills.youtube:run",
    "maps": "clawlite.skills.maps:run",
    "switchbot": "clawlite.skills.switchbot:run",
    "voice-call": "clawlite.skills.voice_call:run",
    "find-skills": "clawlite.skills.find_skills:run",
}

SKILL_DESCRIPTIONS = {
    "coding-agent": "Delega tarefas de código para agentes especializados.",
    "github": "Automação de issues, PRs e repositórios.",
    "gmail": "Busca e rascunho de e-mails.",
    "google-calendar": "Consulta e gestão de calendário.",
    "obsidian": "Leitura e organização de notas locais.",
    "slack": "Integração com canais e mensagens no Slack.",
    "discord": "Integração com servidores e mensagens no Discord.",
    "twitter": "Leitura/produção de conteúdo no X/Twitter.",
    "threads": "Integração com Threads.",
    "web-search": "Busca na web com snippets rápidos.",
    "web-fetch": "Extração de conteúdo legível de URLs.",
    "browser": "Automação de navegador para fluxos web.",
    "docker": "Comandos utilitários para containers Docker.",
    "ssh": "Execução remota via SSH.",
    "supabase": "Operações básicas com Supabase.",
    "firebase": "Operações básicas com Firebase.",
    "aws": "Ações comuns na AWS.",
    "vercel": "Deploy e operações Vercel.",
    "google-drive": "Gerenciamento de arquivos no Drive (list, search, upload, download).",
    "image-gen": "Geração de imagem por IA.",
    "whisper": "Transcrição de áudio com Whisper local ou API OpenAI.",
    "weather": "Consulta de clima atual e previsão.",
    "cron": "Agendamento de tarefas periódicas (add, list, remove, run, status).",
    "skill-creator": "Criação/edição de novas skills.",
    "memory-search": "Busca semântica em memórias/notas.",
    "healthcheck": "Auditoria de saúde e segurança do host.",
    "linear": "Integração com tickets do Linear.",
    "notion": "Integração com páginas e bancos Notion.",
    "tailscale": "Ações utilitárias com Tailscale.",
    "ollama": "Execução local de modelos com Ollama (status, list, generate, pull).",
    "pdf": "Leitura e extração de PDF.",
    "rss": "Leitura de feeds RSS.",
    "youtube": "Busca e resumo de conteúdo no YouTube.",
    "maps": "Consulta de locais e rotas.",
    "switchbot": "Controle de dispositivos SwitchBot.",
    "voice-call": "Fluxos de voz/chamada.",
    "find-skills": "Descoberta de skills disponíveis.",
}


def describe_skill(name: str) -> str:
    return SKILL_DESCRIPTIONS.get(name, "Sem descrição cadastrada.")
