from __future__ import annotations

from pathlib import Path

from clawlite.workspace.identity_enforcer import IdentityEnforcer
from clawlite.workspace.loader import WorkspaceLoader
from clawlite.workspace.user_profile import parse_user_profile_markdown


def test_user_profile_parser_extracts_structured_fields() -> None:
    profile = parse_user_profile_markdown(
        """
        # User Profile

        Name: Eder
        What to call them: Ed
        Pronouns: he/him
        Timezone: America/Sao_Paulo
        Context: ClawLite core work
        Preferences: concise updates, direct actions, mention timezone when relevant

        ## Working Style
        - Prefer concise progress updates
        - Commit and test changes incrementally
        """,
        source_path="/tmp/USER.md",
    )

    assert profile.name == "Eder"
    assert profile.preferred_name == "Ed"
    assert profile.pronouns == "he/him"
    assert profile.timezone == "America/Sao_Paulo"
    assert profile.context == "ClawLite core work"
    assert profile.preferences == [
        "concise updates",
        "direct actions",
        "mention timezone when relevant",
    ]
    assert profile.working_style == [
        "Prefer concise progress updates",
        "Commit and test changes incrementally",
    ]


def test_workspace_loader_exposes_structured_user_profile_prompt(tmp_path: Path) -> None:
    loader = WorkspaceLoader(workspace_path=tmp_path / "ws")
    loader.bootstrap()

    profile = loader.user_profile()
    prompt = loader.user_profile_prompt()

    assert profile.timezone == "UTC"
    assert "[Structured User Profile]" in prompt
    assert "- Timezone: UTC" in prompt
    assert "- Preferences: Clear answers, direct actions, concise updates" in prompt


def test_identity_enforcer_rewrites_provider_intro_and_flags_residual_vendor_contamination(tmp_path: Path) -> None:
    loader = WorkspaceLoader(workspace_path=tmp_path / "ws")
    loader.bootstrap()
    enforcer = IdentityEnforcer(workspace_loader=loader)

    rewritten = enforcer.enforce(
        user_text="resuma o deploy",
        output_text="As an AI language model trained by OpenAI, I can help summarize the rollout.",
    )
    assert rewritten.persist_allowed is True
    assert rewritten.text == "I can help summarize the rollout."
    assert "provider_contamination_rewritten" in rewritten.warnings

    blocked = enforcer.enforce(
        user_text="resuma o deploy",
        output_text="Deployment summary ready. Generated by OpenAI for review.",
    )
    assert blocked.persist_allowed is False
    assert blocked.violations == ["provider_contamination_residual"]
